### PR TITLE
Fix linux gamedata for CBaseServer::RejectConnection

### PR DESCRIPTION
**Pull request by eldoradoel**
I have tested it on Linux and it works fine

### CODE REVIEW

**Comment by tslashd** [comment]
Works for me as well.
Previous [PR](https://github.com/GAMMACASE/ServerRedirect/issues/43#issuecomment-1186507039) for this was still throwing same error

**Comment by GAMMACASE** [comment]
This signature was in my original commit. And it doesn't work on some instances of linux (for example on mine srcds installation on debian). This makes me think there are multiple versions of engine.so existing at the current time, not sure if there was an optional update or smth, but it requires more stuff to be updated to support all the variations of the engine.so.

**Comment by eldoradoel** [comment]
I don't think some of the updates are mandatory on the server side, only the next time Valve forces an update or runs the update manually. There is a similar phenomenon among the community players here, some of which work and some of which don't. I think gamedata should be generated from the latest game files.

**Comment by eldoradoel** [comment]
I don't think some updates are mandatory on the server side, only the next time Valve forces an update or runs the update manually. There is a similar phenomenon among the community players here, some of which work and some of which don't. I think gamedata should be generated from the latest game files.

**Comment by GAMMACASE** [comment]
> I don't think some updates are mandatory on the server side, only the next time Valve forces an update or runs the update manually. There is a similar phenomenon among the community players here, some of which work and some of which don't. I think gamedata should be generated from the latest game files.

Haven't happen to me before, but yeah, old gamedata works on my instance of srcds on linux, so I guess it runs an old engine.so. Although that leaves the question open, why do people come here to get an up to date gamedata when they are running an old engine.so which shouldn't have any troubles then (that was the reason issue #43 was opened and what made me update the sig back to the old binary)

If that's actually the case (old vs new binaries not getting updated for everyone), I can just revert my old commit then, as that is what brought old sig back.

**Comment by GAMMACASE** [comment]
Closing this in a favor of reverting commit that brought the old sig, lmk if there's still anything to add in here.

**Pull request closed without merging**
